[package]
name = "sol_ray_swap"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams = "0.6"
substreams-solana = "0.14"
prost = "0.13"
regex = "1.10"
bs58 = "0.5"

[build-dependencies]
prost-build = "0.13"